import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "App Route Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="px-10">
        <header className="bg-neutral-800 w-full text-center py-4 border border-neutral-700 flex items-center justify-around">
          <div>Universal Header</div>
          <div className="flex items-center gap-4">
            <Link href="/">
              <button className=" border border-white px-5 py-2 rounded-full hover:bg-zinc-800">
                Home
              </button>
            </Link>
            <Link href="/about" prefetch={false}>
              <button className=" border border-white px-5 py-2 rounded-full hover:bg-zinc-800">
                About
              </button>
            </Link>
            <Link href="/blog">
              <button className=" border border-white px-5 py-2 rounded-full hover:bg-zinc-800">
                Blog
              </button>
            </Link>
          </div>
        </header>
        <main>{children}</main>
        <footer className="bg-neutral-800 w-full text-center py-4 border border-neutral-700">
          Universal Footer
        </footer>
      </body>
    </html>
  );
}
